export type Card = {
	id: number;
	sourceId: string;
	name: string;
	cost: number;
	power: number;
	description: string;
	pool: string;
	flavorText: string;
	keyword: string;
	imageLink: string;
};
// cost: 1;
// description: "Ongoing: If you’ve played all 6 stones, Thanos has +10 Power. (wherever he is)";
// id: 127;
// imageLink: "https://dev-getsnapped-images.s3.amazonaws.com/cards/PowerStone.webp";
// name: "Power Stone";
// power: 3;
// s3Bucket: "dev-getsnapped-images";
// s3Key: "cards/PowerStone.webp";
// sourceId: "POOL_5";
